OPENAI_API_KEY = "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"
QDRANT_URL = 'https://8d48fd85-1a96-4a12-aa68-529b01af6f07.us-east4-0.gcp.cloud.qdrant.io'
QDRANT_API_KEY = 'laC5RvUmyTOiRZvezpPBvfyLiPfFJIyKPOe2eX9dMz2u0JI4JqGEHg'
